CIE206PROJECT/Models/Chart/Data.cs
namespace CIE206PROJECT.Models.Chart
{
    public class Data
    {
        public string[] labels { get; set; }
        public Dataset[] datasets { get; set; }
    }
}

CIE206PROJECT/Pages/Admin_Pages/Data.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using Newtonsoft.Json;
using CIE206PROJECT.Models.Chart;


using CIE206PROJECT.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System.Data.SqlClient;

namespace CIE206PROJECT.Pages.Admin_Pages
{
    public class Data : PageModel
    {
		public List<Tuple<int, string, string>> sortingList = new List<Tuple<int, string, string>>();
        [BindProperty]
        public string ChartJson { get; set; }
        public ChartJs Chart { get; set; }

		public ChartJs CriteriaChart { get; set; }
		public ChartJs StudentsChart { get; set; }
		public string criteriaChartJson { get; set; }

		public string studentsChartJson { get; set; }


		private readonly DB_Container _DBC;
		public DataPage _DB { get; set; }
		public DataTable dt { get; set; }
		public string _Handler { get; set; }
		public string data_of { get; set; }
		public string SortingBy { get; set; }

		private readonly ILogger<Data> _logger;


		public void initalizeSortingList()
		{ 
			int i = 0;
			string asc_dsc = string.Empty;
			foreach (DataColumn col in dt.Columns)
			{
				asc_dsc = "Ascending";

				sortingList.Add(new Tuple<int, string, string>(i, col.ColumnName, asc_dsc));
				i++;
				asc_dsc = "Descending";
				sortingList.Add(new Tuple<int, string, string>(i, col.ColumnName, asc_dsc));
				i++;
			}
		}

        public Data(ILogger<Data> logger, DB_Container container)
        {
            data_of= string.Empty;
            _logger = logger;
			SortingBy= "Sort by..";
			_DBC = container;
		}

        public void OnGet()
        {
			OnGetCourses();
		}
        public void OnGetCourses()
        {
			_DB = _DBC.dataPage_DB;
			_Handler = "Course";
			dt = _DB.getCourses();
			initalizeSortingList();
            data_of = "All Courses";
			init_chart_fin();

			//////////////////////////////

		}
		public void OnGetInstuctors()
        {
			_DB = _DBC.dataPage_DB;
			_Handler = "Inst";
			dt = _DB.getTrainerEval();
			initalizeSortingList();
			data_of = "Instructor Ratings";
			init_chart_tut();


		}
		public void OnGetStudents()
		{
			_DB = _DBC.dataPage_DB;
			_Handler = "Stu";
			dt = _DB.getStudentEval();
			initalizeSortingList();
			data_of = "Student Ratings";

		}
		public void OnGetFinances()
        {
			_DB = _DBC.dataPage_DB;
			dt = _DB.getFinances();
			_Handler = "Fin";
			data_of = "Course Finances";
			initalizeSortingList();
			init_chart_fin();

		}

		public void OnGetSort(string itemsort, string sortorder, string dataofin, string hndlr)
		{
			if (hndlr == "Fin")
			{
				_DB = _DBC.dataPage_DB;
				dt = _DB.sortFinances(itemsort, sortorder);
			}
			else if (hndlr == "Inst")
			{
				_DB = _DBC.dataPage_DB;
				dt = _DB.sortTrainerEval(itemsort, sortorder);
			}
			else if (hndlr == "Course")
			{
				_DB = _DBC.dataPage_DB;
				dt = _DB.sortCourses(itemsort, sortorder);

			}
			else if (hndlr == "Stu")
			{
				_DB = _DBC.dataPage_DB;
				dt = _DB.sortStudentEval(itemsort, sortorder);

			}

			data_of = dataofin;
			_Handler = hndlr;
			initalizeSortingList();
			SortingBy = $"{itemsort} {sortorder}";

		}


		private void init_chart_fin()
		{
			_DB = _DBC.dataPage_DB;
			DataTable datachartdt = _DB.getFinances();
			var chartData = @"
				{
				type: 'bar',
				responsive: true,
				data:
				{
				datasets: [{
				backgroundColor: [
				'rgba(255, 99, 132, 0.2)',
				'rgba(54, 162, 235, 0.2)',
				'rgba(157, 207, 170, 0.2)',
				'rgba(218, 137, 232, 0.2)',
				'rgba(160, 240, 156, 0.2)',
				'rgba(131, 27, 250, 0.2)',

				],
				borderColor: [
				'rgba(255, 99, 132, 1)',
				'rgba(54, 162, 235, 1)',
				'rgba(157, 207, 170,1)',
				'rgba(218, 137, 232,1)',
				'rgba(160, 240, 156,1)',
				'rgba(131, 27, 250, 1)',
				],
				borderWidth: 1
				}]
				},
				options:
				{
				scales:
				{
				y: [{
				ticks:
				{
				beginAtZero: true
				}
				}]
				}
				}
				}";
			Chart = JsonConvert.DeserializeObject<ChartJs>(chartData);
			ChartJson = JsonConvert.SerializeObject(Chart, new JsonSerializerSettings
			{


				NullValueHandling = NullValueHandling.Ignore,
			});


			try
			{
				Chart = JsonConvert.DeserializeObject<ChartJs>(chartData);
				List<string> Labels = new List<string> { };
				List<double> Data = new List<double>();
				if (datachartdt is not null)
				{
					foreach (DataRow row in datachartdt.Rows)
					{
						int payment = (int)row["Payed (L.E)"];
						string Couse_Name = (string)row["Course Name"];

						int index = Labels.IndexOf(Couse_Name); // Find the index of the label in the list
						if (index == -1) // Check if the label is not in the list
						{
							Labels.Add(Couse_Name); // Add the label to the list
							Data.Add(payment); // Add the payment to the summedPayments list
						}
						else
						{
							Data[index] += payment; // Add the payment to the existing summed payment
						}
					}
				}

				Chart.data.datasets[0].label = "Courses Payment";
				Chart.data.datasets[0].data = Data.ToArray();
				Chart.data.labels = Labels.ToArray();

				ChartJson = JsonConvert.SerializeObject(Chart, new JsonSerializerSettings
				{
					NullValueHandling = NullValueHandling.Ignore,
				});
			}
			catch (Exception e)
			{
				Console.WriteLine(e.ToString());
				//throwing and exception caused a runtime error so this is a better way to go
				//around it until adding proper exception handling.
			}
		}

		private void init_chart_tut()
		{
			_DB = _DBC.dataPage_DB;
			DataTable datachartdt = _DB.getTrainerEval();
			var chartData = @"
				{
				type: 'bar',
				responsive: true,
				data:
				{
				datasets: [{
				backgroundColor: [
				'rgba(255, 99, 132, 0.2)',
				'rgba(54, 162, 235, 0.2)',
				'rgba(157, 207, 170, 0.2)',
				'rgba(218, 137, 232, 0.2)',
				'rgba(160, 240, 156, 0.2)',
				'rgba(131, 27, 250, 0.2)',

				],
				borderColor: [
				'rgba(255, 99, 132, 1)',
				'rgba(54, 162, 235, 1)',
				'rgba(157, 207, 170,1)',
				'rgba(218, 137, 232,1)',
				'rgba(160, 240, 156,1)',
				'rgba(131, 27, 250, 1)',
				],
				borderWidth: 1
				}]
				},
				options:
				{
				scales:
				{
				y: [{
				ticks:
				{
				beginAtZero: true
				}
				}]
				}
				}
				}";

			try
			{
				CriteriaChart = JsonConvert.DeserializeObject<ChartJs>(chartData);
				StudentsChart = JsonConvert.DeserializeObject<ChartJs>(chartData);
				// Initialize the lists for both charts
				List<string> criteriaLabels = new List<string>();
				List<double> criteriaAverages = new List<double>();
				List<int> criteriaCounts = new List<int>();

				List<string> studentsLabels = new List<string>();
				List<double> studentsAverages = new List<double>();
				List<int> studentsCounts = new List<int>();

				if (datachartdt is not null)
				{
					foreach (DataRow row in datachartdt.Rows)
					{
						string tutorName = (string)row["Tutor Name"];
						int criteria = (int)row["Average Criteria"];
						int students = (int)row["Number of Students"];

						// Update the lists for the criteria chart
						int criteriaIndex = criteriaLabels.IndexOf(tutorName);
						if (criteriaIndex == -1)
						{
							criteriaLabels.Add(tutorName);
							criteriaAverages.Add(criteria);
							criteriaCounts.Add(1);
						}
						else
						{
							criteriaAverages[criteriaIndex] += criteria;
							criteriaCounts[criteriaIndex]++;
						}

						// Update the lists for the students chart
						int studentsIndex = studentsLabels.IndexOf(tutorName);
						if (studentsIndex == -1)
						{
							studentsLabels.Add(tutorName);
							studentsAverages.Add(students);
							studentsCounts.Add(1);
						}
						else
						{
							studentsAverages[studentsIndex] += students;
							studentsCounts[studentsIndex]++;
						}
					}
				}

				// Calculate the average values for both charts
				for (int i = 0; i < criteriaAverages.Count; i++)
				{
					criteriaAverages[i] /= criteriaCounts[i];
				}
				for (int i = 0; i < studentsAverages.Count; i++)
				{
					studentsAverages[i] /= studentsCounts[i];
				}

				// Set the chart data for the criteria chart
				CriteriaChart.data.datasets[0].label = "Average Criteria per Tutor";
				CriteriaChart.data.datasets[0].data = criteriaAverages.ToArray();
				CriteriaChart.data.labels = criteriaLabels.ToArray();

				// Set the chart data for the students chart
				StudentsChart.data.datasets[0].label = "Average Number of Students per Tutor";
				StudentsChart.data.datasets[0].data = studentsAverages.ToArray();
				StudentsChart.data.labels = studentsLabels.ToArray();

				// Serialize the charts
				criteriaChartJson = JsonConvert.SerializeObject(CriteriaChart, new JsonSerializerSettings
				{
					NullValueHandling = NullValueHandling.Ignore,
				});
				studentsChartJson = JsonConvert.SerializeObject(StudentsChart, new JsonSerializerSettings
				{
					NullValueHandling = NullValueHandling.Ignore,
				});
			}
			catch (Exception e)
			{
				Console.WriteLine(e.ToString());
			}
		}
	}
}

CIE206PROJECT/Pages/Admin_Pages/Graphs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CIE206PROJECT.Pages.Admin_Pages
{
    public class Graphs : PageModel
    {
        private readonly ILogger<Graphs> _logger;

        public Graphs(ILogger<Graphs> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CIE206PROJECT/Pages/Admin_Pages/RequestsApproval.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Data;
using CIE206PROJECT.Controllers;

namespace CIE206PROJECT.Pages.Admin_Pages
{
    public class RequestsApproval : PageModel
    {
        public DataTable dt {set; get;}
        
        private readonly DB_Container _DBC;
        private readonly LoginController _LC;
        private RequestsPage _DB;
        private readonly ILogger<RequestsApproval> _logger;

        [BindProperty(SupportsGet =true)]
        public string content { get; set; } 

        public RequestsApproval(ILogger<RequestsApproval> logger, DB_Container container, LoginController _loginController)
        {
            _logger = logger;
            _DBC = container;
            _LC = _loginController;
        }

        public void OnGet()
        {
            _DB = _DBC.requestsPage_DB;
            dt = _DB.getRequests(_LC.GetLoggedInUserId());
        }


    public IActionResult OnPost(int rowIndex, string actionType)
    {
        if (actionType == "accept")
        {
        }
        else if (actionType == "deny")
        {
        }
        Console.WriteLine($"{rowIndex},{actionType}" );
        return RedirectToPage();
    }




    }
}

CIE206PROJECT/Pages/Admin_Pages/Send_Request.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using CIE206PROJECT.Controllers;
using CIE206PROJECT.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CIE206PROJECT.Pages.Admin_Pages
{
    public class Send_Request : PageModel
    {
        private readonly DB_Container _DBC;
        private readonly LoginController _LC;
        public RequestsPage _DB { get; set; }

        [BindProperty(SupportsGet =true)]
        public Request req { get; set; }

        [BindProperty(SupportsGet = true)]
        public string errorstring  { get; set; }
        
        [BindProperty]
        public int SendTo { get; set; }
        [BindProperty]
        public string MsgSubject { get; set; }
        [BindProperty]
        public string MsgContent { get; set; }
        private readonly ILogger<Send_Request> _logger;

        public Send_Request(ILogger<Send_Request> logger, DB_Container container, LoginController _loginController)
        {
            _logger = logger;
            _DBC = container;
            _LC = _loginController;
        }

        public void OnGet()
        {
            _DB = _DBC.requestsPage_DB;
        }

        public bool isadmin()
        {
            return _LC.IsAdmin();
        }
        public IActionResult OnPostSendRequest()
        {
                _DB = _DBC.requestsPage_DB;
                req.subject = MsgSubject;
                req.content = MsgContent;
                req.request_id = _DB.getMaxReqID() + 1;
                req.sent_by = _LC.GetLoggedInUserId();
                req.datetime = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");
                if (SendTo == 1) { 
                    req.sent_to = _DB.getSSID() ;
                }
                else {
                    req.sent_to =  _DB.getCEOID();
                }
                if (!_DB.addRequest(req))
                {
                    string err = "YOUR REQUEST WAS NOT ACCEPTED";
                    return RedirectToPage("/Admin_Pages/Send_Request", new { req = req, errorstring =  err});
                }
                else
                {
                    string err = "YOUR REQUEST WAS SENT, SEND ANOTHER?";
                    return RedirectToPage("/Admin_Pages/Send_Request", new {errorstring = err, req = new Request() });
                }
        }
    }
}

CIE206PROJECT/Pages/Admin_Pages/Data.cshtml
@page
@model CIE206PROJECT.Pages.Admin_Pages.Data
@using System.Data

@{
	Layout = "_AdminLayout";
}
@using CIE206PROJECT.Controllers
@inject LoginController lc

@if (!lc.IsLoggedIn())
{
    <script>
        window.location.href = "/index";
    </script>
}
else
{

<div class="container">
	<!-- Tabs navs -->
	<div class="card">
		<div class="card-body">


			<div class="row ">
				<div class="col-auto  me-sm-auto px-0 px-sm-2">
					<ul class="nav nav-tabs mb-3" id="ex1" role="tablist">
						<li class="nav-item" role="presentation">
							<a class="nav-link active" id="ex1-tab-1" data-mdb-toggle="tab" href="#ex1-tabs-1"
								role="tab" aria-controls="ex1-tabs-1" aria-selected="true">Raw Data</a>
						</li>
						<li class="nav-item" role="presentation">
							<a class="nav-link" id="ex1-tab-2" data-mdb-toggle="tab" href="#ex1-tabs-2" role="tab"
								aria-controls="ex1-tabs-2" aria-selected="false">Graphs</a>
						</li>
					</ul>
				</div>
				<div class="col-auto  ms-sm-auto d-flex justify-content-end text-center px-0 px-sm-2">
					<div class="dropdown  ">
						<button class="btn btn-outline-secondary dropdown-toggle text-center" type="button"
							id="dropdownMenuButton" data-mdb-toggle="dropdown" aria-expanded="false">
							Data From
						</button>
						<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<li><a class="dropdown-item" asp-page-handler="Courses">Courses</a></li>
							<li><a class="dropdown-item" asp-page-handler="Finances">Finances</a></li>
							<li><a class="dropdown-item" asp-page-handler="Instuctors">Instuctor Rating</a></li>
							<li><a class="dropdown-item" asp-page-handler="Students">Students Rating</a></li>

						</ul>
					</div>
				</div>
			</div>
			<!-- Tabs navs -->
			<!-- Tabs content -->
			<div class="tab-content" id="ex1-content">
				<div class="tab-pane fade show active" id="ex1-tabs-1" role="tabpanel" aria-labelledby="ex1-tab-1">




					<div class="row justify-content-center g-2">

						<div class="col">
							<h1 class="display-4 text-center">@Model.data_of</h1>
							<hr class="hr hr-blurry" />

						</div>
					</div>

					<div class="row mt-5">

						<div class="col-xxl-8 col-12 ">
							<div class="mb-3">
								<input type="text" class="form-control" id="searchInput" placeholder="Search..">
							</div>
						</div>
						<div class="col-xxl-3 col-12 mb-3">
							<div class="d-grid gap-2 ">

								<button class="btn btn-outline-secondary dropdown-toggle text-center" type="button"
									id="dropdownMenuButton" data-mdb-toggle="dropdown" aria-expanded="false">
									@Model.SortingBy
								</button>

								<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
									@foreach (var elem in @Model.sortingList)
									{
										<li><a class="dropdown-item" asp-page-handler="Sort"
												asp-route-itemsort="@elem.Item2" asp-route-sortorder="@elem.Item3"
												asp-route-dataofin="@Model.data_of"
												asp-route-hndlr="@Model._Handler">@elem.Item2 @elem.Item3 </a></li>
									}
								</ul>
							</div>
						</div>
						<div class="col-xxl-1 col-12 ">
							<div class="d-grid gap-2 ">
								<button onclick="searchTable()" class="btn btn-secondary">Search</button>
							</div>
						</div>
					</div>
					<div class="row table-res">
						<table class="table table-striped">
							<thead>
								<tr>
									<th></th>
									@foreach (DataColumn col in Model.dt.Columns)
									{
										<th scope="col">@col.ColumnName</th>
									}
								</tr>
							</thead>
							<tbody>
								@for (int ii = 0; ii < @Model.dt.Rows.Count; ii++)
								{
									<tr class="table-row">
										<th scope="row">@ii</th>
										@for (int j = 0; j < @Model.dt.Columns.Count; j++)
										{
											<td>@Model.dt.Rows[ii][j].ToString()</td>
										}
									</tr>
								}
							</tbody>
						</table>
					</div>

				</div>
			</div>

			<div class="tab-pane fade" id="ex1-tabs-2" role="tabpanel" aria-labelledby="ex1-tab-2">
				<div class="tab-pane fade show" id="ex1-tabs-1" role="tabpanel" aria-labelledby="ex1-tab-1">
					<div class="row justify-content-center g-2">
						<div class="col">
							<h1 class="display-4 text-center">@Model.data_of</h1>
							<hr class="hr hr-blurry mb-0" />

						</div>
					</div>
			<div class="row mt-5">
				<div class="col">
					<div class="chart-container @(string.IsNullOrEmpty(Model.ChartJson) ? "hidden" : "")" width="600" height="400">
						<canvas id="barChart"></canvas>
					</div>
				</div>
			</div>
			<div class="row mt-5">
				<div class="col">
					<div class="chart-container @(string.IsNullOrEmpty(Model.criteriaChartJson) ? "hidden" : "")" width="600" height="400">
						<canvas id="criteriaChart" width="600" height="400"></canvas>
					</div>
				</div>
			</div>
			<div class="row mt-5">
				<div class="col">
					<div class="chart-container @(string.IsNullOrEmpty(Model.studentsChartJson) ? "hidden" : "")" width="600" height="400">
						<canvas id="studentsChart" width="600" height="400"></canvas>
					</div>
				</div>
			</div>

				</div>
			</div>
			<!-- Tabs content -->
		</div>
	</div>
</div>

@section Scripts {
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

	<script type="module">
		document.addEventListener('DOMContentLoaded', (event) => {
			var ctx = document.getElementById('criteriaChart');
			var myChart = new Chart(ctx, @Html.Raw(Model.criteriaChartJson) );
		});
	</script>
	<script type="module">
		document.addEventListener('DOMContentLoaded', (event) => {
			var ctx = document.getElementById('studentsChart');
			var myChart = new Chart(ctx, @Html.Raw(Model.studentsChartJson) );
		});
	</script>

	<script type="module">
		document.addEventListener('DOMContentLoaded', (event) => {
			var ctx = document.getElementById('barChart');
			var myChart = new Chart(ctx, @Html.Raw(Model.ChartJson) );
		});
	</script>


	<script>
		function searchTable() {
			const input = document.getElementById('searchInput').value.toLowerCase();
			const rows = document.getElementsByClassName('table-row');
			let firstMatch = null;

			// Clear all previous highlights
			for (let row of rows) {
				row.classList.remove('highlight');
			}

			if (input.trim() === '') {
				return; // Exit early if the input is empty
			}

			for (let row of rows) {
				const cells = row.getElementsByTagName('td');
				let rowMatched = false;

				for (let cell of cells) {
					const cellText = cell.innerText.toLowerCase();
					if (cellText.includes(input)) {
						rowMatched = true;
						if (firstMatch === null) {
							firstMatch = row;
						}
						break;
					}
				}

				if (rowMatched) {
					row.classList.add('highlight');
				}
			}

			if (firstMatch !== null) {
				firstMatch.scrollIntoView({
					behavior: 'smooth',
					block: 'start'
				});
			} else {
				alert('No matching rows found.');
			}
		}
	</script>



}


<style>
	.highlight {
		background-color: yellow;
		animation: fadeOut 10s forwards;
	}

	@@keyframes fadeOut {
		0% {
			background-color: yellow;
		}

		100% {
			background-color: transparent;
		}
	}

	.chart-container.hidden {
		display: none;
	}
</style>




}

CIE206PROJECT/Pages/Admin_Pages/Send_Request.cshtml
@page
@model CIE206PROJECT.Pages.Admin_Pages.Send_Request
@{
    if (Model.isadmin())
    {

        Layout = "_AdminLayout";
    }
    else
    {
        Layout = "_StudentLayout";

    }
}


@using CIE206PROJECT.Controllers
@inject LoginController lc

@if (!lc.IsLoggedIn())
{
    <script>
        window.location.href = "/index";
    </script>
}
else
{

<div class="container-sm mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <form asp-page-handler="SendRequest" method="post">
                    <div class="row mb-4">
                        <div class="col-12">
                            <h2 class="card-title">Request Subject</h2>
                            <div class="input-group mb-2">
                                <input  required type="text" class="form-control" placeholder="Subject" value="@Model.req.subject" asp-for="@Model.req.subject" />
                            </div>
                        </div>
                    </div>

                    <div class="row my-4">
                        <div class="col-12">
                            <h2>Request description</h2>
                            <div class="form-outline mb-2">
                                <textarea required class="form-control" id="textAreaExample" rows="6" value="@Model.req.content" asp-for="@Model.req.content"></textarea>
                                <label class="form-label" for="textAreaExample">Message</label>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <span class="rounded rounded-4 shadow-sm py-0 px-4">
                            <div class="row">
                                <div class="col p-3">
                                    <h3>
                                        Send To:
                                    </h3>
                                    <!-- Default radio button -->
                                    <div class="form-check">
                                        <input required class="form-check-input" type="radio" name="SentTo" id="ceoRadio" value="1" asp-for="@Model.SendTo" />
                                        <label class="form-check-label" for="ceoRadio">CEO</label>
                                    </div>

                                    <!-- Checked radio button -->
                                    <div class="form-check">
                                        <input required class="form-check-input" type="radio" name="SentTo" id="seniorSupervisorRadio" value="2" asp-for="@Model.SendTo" />
                                        <label class="form-check-label" for="seniorSupervisorRadio">Senior Supervisor</label>
                                    </div>
                                </div>
                                <div class="col-12 col-xl-2 p-2 ps-0 m-0 mb-2">
                                    <button type="submit" class="btn btn-outline-primary h-50 w-100 m-2">Submit</button>
                                    <div class="form-check ms-0">
                                        <input  class="ms-0 form-check-input" type="checkbox" value="" id="includeEmailCheckbox" checked />
                                        <label class="form-check-label ms-0" for="includeEmailCheckbox">Include Email</label>
                                    </div>
                                </div>
                            </div>
                        <h3 class = "lead">@Model.errorstring</h3>
                        </span>
                    </div>
           
                </form>
            </div>
        </div>
    </div>
</div>


}